name: dobon_calculator
description: ドボン電卓
publish_to: 'none'

version: 0.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.2

  # DI Tools
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Code Generator
  freezed: ^2.4.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  custom_lint:
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true